# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65d3e805c0d6620988850edaf37e04683424d4a2eebb53ee687f58d6b55fd534e0a3bf03948f6b97a3e2c8bd501ecbfd5b0cdfea99f27d4e19df8509ece68a3e

test:
  secret_key_base: d18f9900eaf612c4451d9821930e365e3080a1f112bfd5d04098b4f9c6e6f3850a1ce4053b5280dd4680f186df7bfb3289f52ca2853081c4cf58edaa02fc4034

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
